"""

Revision ID: 33ece2a2d8da
Revises: aaa538e0652d
Create Date: 2025-02-09 10:23:45.536961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ece2a2d8da'
down_revision: Union[str, None] = 'aaa538e0652d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('workshop_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'workshop_id')
    # ### end Alembic commands ###
