"""

Revision ID: aaa538e0652d
Revises: 379bab5c0648
Create Date: 2025-02-09 09:58:43.023318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa538e0652d'
down_revision: Union[str, None] = '379bab5c0648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'date')
    # ### end Alembic commands ###
