"""

Revision ID: d70db5b5265e
Revises: 6362417d223e
Create Date: 2024-11-15 21:46:25.581246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70db5b5265e'
down_revision: Union[str, None] = '6362417d223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectors', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectors', 'created_at')
    # ### end Alembic commands ###
